import { useState } from "react";
import API from "../services/api";
import PageLayout from "../components/PageLayout";
import ReactMarkdown from "react-markdown";

function UploadResume() {
  const [file, setFile] = useState(null);
  const [analysis, setAnalysis] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleUpload = async () => {
    try {
      if (!file) {
        alert("Please select a PDF file");
        return;
      }

      setError("");
      setLoading(true);

      const formData = new FormData();
      formData.append("resume", file);

      const token = localStorage.getItem("token");

      const res = await API.post(
        "/analysis/upload",
        formData,
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      setAnalysis(
        res.data.savedAnalysis.analysis
      );

      alert("Analysis Completed");
    } catch (error) {
      console.log(error);
      setError("Upload Failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <PageLayout>
     <div className="max-w-5xl mx-auto px-2 md:px-0">

        <div className="mb-8">
      <h1 className="text-2xl md:text-4xl font-bold text-gray-800">
            Upload Resume
          </h1>

          <p className="text-gray-500 mt-2">
            Upload your resume and receive AI-powered feedback and improvement suggestions.
          </p>
        </div>

   <div className="bg-white rounded-3xl shadow-lg p-4 md:p-8">

          <h2 className="text-2xl font-semibold text-gray-800 mb-4">
            Upload Resume
          </h2>

          <p className="text-gray-500 mb-6">
            Supported Format: PDF
          </p>

         <div className="w-full">

  <label
    htmlFor="resume"
    className="
      cursor-pointer
      inline-block
      bg-purple-700
      text-white
      px-5
      py-3
      rounded-xl
      hover:bg-purple-800
      transition
    "
  >
    Choose Resume
  </label>

  <input
    id="resume"
    type="file"
    accept=".pdf"
    onChange={(e) =>
      setFile(e.target.files[0])
    }
    className="hidden"
  />

  {file && (
    <p className="mt-3 text-sm text-gray-600 break-all">
      📄 {file.name}
    </p>
  )}

</div>

          {file && (
            <p className="text-sm text-gray-600 mt-4">
              Selected File: {file.name}
            </p>
          )}

          <button
            onClick={handleUpload}
            disabled={loading}
            className="
              mt-6
              bg-purple-700
              text-white
              px-6
              py-3
              rounded-xl
              hover:bg-purple-800
              transition
              disabled:opacity-50
            "
          >
            {loading
              ? "Analyzing..."
              : "Analyze Resume"}
          </button>

          {error && (
            <p className="text-red-500 mt-4">
              {error}
            </p>
          )}

        </div>

        {analysis && (
          <div className="
            bg-white
            rounded-3xl
            shadow-lg
            p-8
            mt-8
          ">

            <div className="
              flex
              justify-between
              items-center
              border-b
              pb-4
              mb-6
            ">

              <div>
                <h2 className="
                  text-2xl
                  font-bold
                  text-purple-700
                ">
                  Resume Analysis Report
                </h2>

                <p className="
                  text-sm
                  text-gray-500
                ">
                  Generated by AI
                </p>
              </div>

              <span className="text-sm text-gray-500">
                {new Date().toLocaleString(
                  "en-IN",
                  {
                    day: "numeric",
                    month: "short",
                    year: "numeric",
                    hour: "numeric",
                    minute: "2-digit",
                  }
                )}
              </span>

            </div>

            <div className="
              text-gray-700
              leading-8
            ">
              <ReactMarkdown
  components={{
    h1: ({ children }) => (
      <h1 className="text-3xl font-bold text-gray-900 mt-8 mb-4">
        {children}
      </h1>
    ),

    h2: ({ children }) => (
      <h2 className="text-2xl font-semibold text-purple-700 mt-6 mb-3">
        {children}
      </h2>
    ),

    p: ({ children }) => (
      <p className="text-gray-700 leading-8 mb-4">
        {children}
      </p>
    ),

    ul: ({ children }) => (
      <ul className="list-disc pl-6 mb-5">
        {children}
      </ul>
    ),

    li: ({ children }) => (
      <li className="text-gray-700 mb-2">
        {children}
      </li>
    ),

    strong: ({ children }) => (
      <strong className="font-semibold text-gray-900">
        {children}
      </strong>
    ),
  }}
>
  {analysis}
</ReactMarkdown>
            </div>

          </div>
        )}

      </div>
    </PageLayout>
  );
}

export default UploadResume;